### ISSUE TITLE
Cppm path!

### ISSUE THREAD

**Issue by Maou-Shimazu** [Maou-Shimazu/Cpp-Project-Manager#39]
Change the config path for cppm to `$HOME/.cppm/`. 
Configure everything to work properly with this change.

**Comment by BrandonDoesDev** [comment]
What's the current config path?

**Comment by Maou-Shimazu** [comment]
@BrandonDoesDev Its ` C:\Users\{user}\AppData\Roaming\cppm` (windows, located at the alternative on unix) referenced [here](https://github.com/Maou-Shimazu/Cpp-Project-Manager/blob/main/src/cppm.rs#L92)
