### ISSUE TITLE
Default code editor

### ISSUE THREAD

**Issue by Maou-Shimazu** [Maou-Shimazu/Cpp-Project-Manager#43]
Ask user for default code editor, should be available in the editor aliases or user should know the command call.
Implement opening if the user passes an editor or the default exists, otherwise error.
Reference to [Open function](https://github.com/Maou-Shimazu/Cpp-Project-Manager/blob/main/src/cppm.rs#L248)

**Comment by BrandonDoesDev** [comment]
#58 #59
