### ISSUE TITLE
Overwriting Non Project Directories

### ISSUE THREAD

**Issue by Maou-Shimazu** [Maou-Shimazu/Cpp-Project-Manager#6]
Panic if there is a directory that exists with the same name

**Comment by BrandonDoesDev** [comment]
If there's a directory that exists with the same name in the current directory or the entire system?

**Comment by Maou-Shimazu** [comment]
> If there's a directory that exists with the same name in the current directory or the entire system?

Current directory, there will need to be an implementation for when they try to open folders with the same name as well though.

**Comment by Maou-Shimazu** [comment]
The program will now panic if there is a folder created with the same name until there is a valid implementation of being able to assign multiple paths to 1 project name.
